(define (empty? xs) (= 0 (length xs)))

(define (compose . fs)
  (lambda (x) (fold-right (lambda (f x) (f x)) x fs)))

(define (sort-pair p) (if (> (first p) (second p)) (reverse p) p))

(define (insert-sort numbers)
  (define (sort-into-iter x smaller larger)
    (if (or (empty? larger) (<= x (first larger)))
      (append smaller (list x) larger)
      (sort-into-iter x (append smaller (list (first larger))) (cdr larger))))
  (define (sort-into x sorted) (sort-into-iter x '() sorted))
  (define (sort-iter unsorted sorted)
    (if (empty? unsorted)
      sorted
      (sort-iter (cdr unsorted) (sort-into (car unsorted) sorted))))
  (sort-iter numbers '()))

(define (select-sort numbers)
  (define (put-smallest-first-iter left right candidate)
    (if (empty? left)
      (cons candidate right)
      (let* ((n (first left)) (smaller (min candidate n)) (bigger (max candidate n)))
        (put-smallest-first-iter (cdr left) (cons bigger right) smaller))))
  (define (put-smallest-first xs) (put-smallest-first-iter (cdr xs) '() (car xs)))
  (define (sort-iter unsorted sorted)
    (if (>= 1 (length unsorted))
      (append sorted unsorted)
      (let* (
        (p (put-smallest-first unsorted))
        (next-smallest (first p))
        (remainder (cdr p)))
          (sort-iter remainder (append sorted `(,next-smallest))))))
  (sort-iter numbers '()))
